export const TYPES = {
	ADD_TO_BASKET: "ADD_TO_BASKET",
	GET_BASKET: "GET_BASKET",
	RESET_BASKET: "RESET_BASKET",
	CHANGE_SHIPPING_METHOD: "CHANGE_SHIPPING_METHOD",
	UPDATE_TOTAL_PRICE: 'UPDATE_TOTAL_PRICE',
	UPDATE_INVALID_ITEMS: 'UPDATE_INVALID_ITEMS',
	
	GET_PROFILE: "GET_PROFILE",

	GET_ORDER: "GET_ORDER",
	ADD_SUBSCRIPTION: "ADD_SUBSCRIPTION",
	UPDATE_SHIPPING_METHOD: "UPDATE_SHIPPING_METHOD",
	UPDATE_PAYMENT_TYPE: "UPDATE_PAYMENT_TYPE",
	UPDATE_DELIVERY_ADDRESS_ID: "UPDATE_DELIVERY_ADDRESS_ID",
	UPDATE_GIFT_MESSAGE: "UPDATE_GIFT_MESSAGE",
	UPDATE_SPECEAL_REQUEST: "UPDATE_SPECEAL_REQUEST",
	UPDATE_DELIVERY_DATETIME: "UPDATE_DELIVERY_DATETIME",
	UPDATE_DELIVERY_FREQUENCy: "UPDATE_DELIVERY_FREQUENCy",
	UPDATE_PRODUCT_VALIDITY: 'UPDATE_PRODUCT_VALIDITY'
};
